param(
  [Parameter(Mandatory=$true)][string]$BaseUrl,
  [Parameter(Mandatory=$true)][string]$TenantId,
  [Parameter(Mandatory=$true)][string]$Email,
  [Parameter(Mandatory=$true)][securestring]$Password,
  [Parameter(Mandatory=$true)][string]$DatabaseUrl,
  [switch]$SkipDashboardBuild,
  [switch]$KeepRestoreContainer
)
$ErrorActionPreference='Stop'
function Write-Step([string]$m){Write-Host "[GA-07] $m"}
function Assert-True([bool]$c,[string]$m){if(-not $c){throw $m}}
function Convert-Secure([securestring]$s){$b=[Runtime.InteropServices.Marshal]::SecureStringToBSTR($s);try{[Runtime.InteropServices.Marshal]::PtrToStringBSTR($b)}finally{[Runtime.InteropServices.Marshal]::ZeroFreeBSTR($b)}}
function Get-Sha([string]$p){(Get-FileHash -Algorithm SHA256 -Path $p).Hash.ToLowerInvariant()}
function Invoke-Docker([string[]]$Arguments,[string]$Failure){$global:LASTEXITCODE=0;$o=docker @Arguments;if($LASTEXITCODE-ne 0){throw $Failure};$global:LASTEXITCODE=0;return $o}
function Invoke-DockerQuiet([string[]]$Arguments,[string]$Failure){$global:LASTEXITCODE=0;docker @Arguments|Out-Null;if($LASTEXITCODE-ne 0){throw $Failure};$global:LASTEXITCODE=0}
function Convert-LastJson($Output,[string]$Failure){$rows=@($Output|ForEach-Object{[string]$_});for($i=$rows.Count-1;$i-ge 0;$i--){$line=$rows[$i].Trim();if([string]::IsNullOrWhiteSpace($line)){continue};if($line -match '^(BEGIN|COMMIT|ROLLBACK|SET)$'){continue};try{return ($line|ConvertFrom-Json)}catch{}};throw $Failure}
function Invoke-DbJsonFile([string]$Path,[hashtable]$Vars){$dir=(Resolve-Path(Split-Path -Parent $Path)).Path;$name=Split-Path -Leaf $Path;$a=@('run','--rm','--env',"DATABASE_URL=$DatabaseUrl",'-v',"${dir}:/sql:ro",'postgres:17','psql',$DatabaseUrl,'-tA','-v','ON_ERROR_STOP=1');foreach($k in $Vars.Keys){$a+=@('-v',"$k=$($Vars[$k])")};$a+=@('-f',"/sql/$name");$o=Invoke-Docker $a "Database SQL failed: $name";return Convert-LastJson $o "Database SQL did not return JSON: $name"}
function Wait-Restore([string]$Name){for($i=0;$i-lt 60;$i++){$global:LASTEXITCODE=0;docker exec -e PGPASSWORD=solidpos $Name pg_isready -h 127.0.0.1 -p 5432 -U postgres -d solidpos_restore|Out-Null;if($LASTEXITCODE-eq 0){return};Start-Sleep -Seconds 1};throw 'Isolated restore PostgreSQL did not become ready.'}
function Restore-Psql([string]$Name,[string[]]$PsqlArguments,[bool]$Output=$false){$a=@('exec','-e','PGPASSWORD=solidpos',$Name,'psql','-h','127.0.0.1','-p','5432','-U','postgres','-d','solidpos_restore')+$PsqlArguments;if($Output){return Invoke-Docker $a 'Isolated restore psql failed.'};Invoke-DockerQuiet $a 'Isolated restore psql failed.'}

$base=$BaseUrl.TrimEnd('/');$plain=Convert-Secure $Password;$scriptRoot=Split-Path -Parent $PSCommandPath;$repoRoot=Resolve-Path(Join-Path $scriptRoot '..\..')
$ga06Validator=Join-Path $scriptRoot 'validate-ga-06-stable-channel-promotion-cohort-update-dry-run.ps1'
$ga06Manifest=Join-Path $repoRoot '.runtime\ga-06-stable-channel-promotion-cohort-update-dry-run\ga-06-manifest.json'
$sourceSql=Join-Path $scriptRoot 'ga-07-source-and-final-check.sql';$rollbackSql=Join-Path $scriptRoot 'ga-07-stable-release-rollback-transaction-drill.sql';$auditSql=Join-Path $scriptRoot 'ga-07-rollback-audit.sql'
$runtime=Join-Path $repoRoot '.runtime\ga-07-backup-restore-rollback-disaster-recovery';$backupDir=Join-Path $runtime 'backup';$manifestPath=Join-Path $runtime 'ga-07-manifest.json';$snapshotPath=Join-Path $runtime 'ga-07-snapshot.json';$evidencePath=Join-Path $runtime 'ga-07-evidence.md';$logPath=Join-Path $repoRoot 'docs\ga\logs\ga-07-backup-restore-rollback-disaster-recovery-log.md'
$backupName='solidpos-ga07-pos-full.dump';$backupPath=Join-Path $backupDir $backupName;$restoreContainer="solidpos-ga07-restore-$(([guid]::NewGuid().ToString('N')).Substring(0,12))";$containerStarted=$false;$traceId="ga07-drill-$(([guid]::NewGuid().ToString('N')).Substring(0,16))"
$RtoTargetSeconds=900;$RpoTargetSeconds=300
Remove-Item -Recurse -Force $runtime -ErrorAction SilentlyContinue;New-Item -ItemType Directory -Force -Path $backupDir,(Split-Path -Parent $logPath)|Out-Null
try{
 Write-Step 'Repository/document GA-07 guardrails...'
 foreach($p in @($ga06Validator,$sourceSql,$rollbackSql,$auditSql,(Join-Path $repoRoot 'SOLIDPOS_GA_07_BACKUP_RESTORE_ROLLBACK_AND_DISASTER_RECOVERY.md'))){Assert-True(Test-Path $p)"Required GA-07 asset missing: $p"}
 Assert-True($DatabaseUrl.StartsWith('postgres://')-or $DatabaseUrl.StartsWith('postgresql://'))'DATABASE_URL must be PostgreSQL.'
 Write-Step 'Repository/document GA-07 guardrails PASS'
 Write-Step 'Secret scan...';$secretScanScript=Join-Path $repoRoot 'scripts\security\scan-local-secrets.ps1';Unblock-File $secretScanScript -ErrorAction SilentlyContinue;$global:LASTEXITCODE=0;& $secretScanScript -Root $repoRoot;$secretScanExitCode=$LASTEXITCODE;$global:LASTEXITCODE=0;if($null-ne$secretScanExitCode-and[int]$secretScanExitCode-ne 0){throw "Secret scan failed: exitCode=$secretScanExitCode"};Write-Step 'Secret scan PASS'
 Write-Step 'Fresh GA-06 prerequisite revalidation...';Unblock-File $ga06Validator -ErrorAction SilentlyContinue;$global:LASTEXITCODE=0;& $ga06Validator -BaseUrl $base -TenantId $TenantId -Email $Email -Password $Password -DatabaseUrl $DatabaseUrl -SkipDashboardBuild:$SkipDashboardBuild;$ga06ExitCode=$LASTEXITCODE;$global:LASTEXITCODE=0;if($null-ne$ga06ExitCode-and[int]$ga06ExitCode-ne 0){throw "GA-06 prerequisite failed: exitCode=$ga06ExitCode"};Assert-True(Test-Path $ga06Manifest)'GA-06 manifest missing.';$ga06=Get-Content -Raw $ga06Manifest|ConvertFrom-Json;Assert-True($ga06.status -eq 'PASS GA STABLE CHANNEL PROMOTION COHORT DRY RUN / GO GA-07')'GA-06 prerequisite status mismatch.';Write-Step 'Fresh GA-06 prerequisite revalidation PASS'
 Write-Step 'Docker / PostgreSQL 17 backup tooling...';Invoke-DockerQuiet @('version') 'Docker is required.';Invoke-DockerQuiet @('run','--rm','postgres:17','pg_dump','--version') 'pg_dump 17 required.';Invoke-DockerQuiet @('run','--rm','postgres:17','pg_restore','--version') 'pg_restore 17 required.';Write-Step 'Docker / PostgreSQL 17 backup tooling PASS'
 Write-Step 'Production health/authentication baseline...';$live=Invoke-RestMethod -Method Get -Uri "$base/health/live" -TimeoutSec 30;$ready=Invoke-RestMethod -Method Get -Uri "$base/health/ready" -TimeoutSec 30;Assert-True($live.status-eq'alive')'Liveness failed.';Assert-True($ready.status-eq'ready'-and$ready.database-eq'ready')'Readiness failed.';$session=Invoke-RestMethod -Method Post -Uri "$base/api/v1/auth/login" -ContentType 'application/json' -Body (@{email=$Email;password=$plain;tenantId=$TenantId}|ConvertTo-Json) -TimeoutSec 30;$headers=@{Authorization="Bearer $($session.accessToken)"};Assert-True(-not[string]::IsNullOrWhiteSpace($session.accessToken))'Login failed.';$contract=Invoke-RestMethod -Method Get -Uri "$base/api/v1/sync/contract" -Headers $headers -TimeoutSec 30;Assert-True([int]$contract.currentSchemaVersion-eq 4)'schemaVersion must be 4.';Write-Step 'Production health/authentication baseline PASS'
 Write-Step 'GA-07 production source snapshot / rollback artifact gate...';$source=Invoke-DbJsonFile $sourceSql @{tenant_id=$TenantId};Assert-True($source.ga07SqlDecision-eq'GO')"GA-07 source blockers: $($source.blockers -join ', ')";Assert-True([string]$source.stableReleaseId-eq[string]$ga06.stableReleaseId)'Stable release drifted from GA-06.';Assert-True([string]$source.rollbackVersion-eq[string]$ga06.rollbackVersion)'Rollback version drifted from GA-06.';Write-Step 'GA-07 production source snapshot / rollback artifact gate PASS'
 Write-Step 'Create full logical pos backup...';$backupStart=Get-Date;if(Test-Path $backupPath){Remove-Item -Force $backupPath};$resolvedBackup=(Resolve-Path $backupDir).Path;Invoke-DockerQuiet @('run','--rm','-v',"${resolvedBackup}:/backup",'postgres:17','pg_dump',$DatabaseUrl,'--schema=pos','--format=custom','--compress=6','--no-owner','--no-privileges','--file',"/backup/$backupName") 'Full logical pg_dump failed.';$backupCompleted=Get-Date;Assert-True(Test-Path $backupPath)'Backup file was not created.';$backupBytes=(Get-Item $backupPath).Length;Assert-True($backupBytes-gt 10000)'Backup file is unexpectedly small.';$backupSha=Get-Sha $backupPath;$list=Invoke-Docker @('run','--rm','-v',"${resolvedBackup}:/backup:ro",'postgres:17','pg_restore','--list',"/backup/$backupName") 'Backup readability verification failed.';Assert-True(($list -join "`n") -match 'TABLE DATA pos sales')'Backup does not contain sales table data.';Assert-True(($list -join "`n") -match 'TABLE DATA pos update_releases')'Backup does not contain update release data.';$captured=[datetimeoffset]::Parse([string]$source.capturedAt);$rpo=[math]::Round(($backupCompleted.ToUniversalTime()-$captured.UtcDateTime).TotalSeconds,3);Assert-True($rpo-ge 0-and$rpo-le$RpoTargetSeconds)"RPO target exceeded: ${rpo}s > ${RpoTargetSeconds}s";Write-Step "Create full logical pos backup PASS; bytes=$backupBytes; rpoSeconds=$rpo"
 Write-Step 'Restore full backup into isolated PostgreSQL...';$restoreStart=Get-Date;Invoke-Docker @('run','-d','--name',$restoreContainer,'-e','POSTGRES_PASSWORD=solidpos','-e','POSTGRES_DB=solidpos_restore','postgres:17') 'Could not start restore container.'|Out-Null;$containerStarted=$true;Wait-Restore $restoreContainer;Invoke-DockerQuiet @('cp',$backupPath,"${restoreContainer}:/tmp/$backupName") 'Could not copy backup.';$extensionBootstrap='CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public; CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;';Restore-Psql -Name $restoreContainer -PsqlArguments @('-v','ON_ERROR_STOP=1','-c',$extensionBootstrap);$extensionCheck=Restore-Psql -Name $restoreContainer -PsqlArguments @('-tA','-v','ON_ERROR_STOP=1','-c',"SELECT json_build_object('citext',EXISTS(SELECT 1 FROM pg_extension WHERE extname='citext'),'pgcrypto',EXISTS(SELECT 1 FROM pg_extension WHERE extname='pgcrypto'))::text;") -Output $true;$extensions=Convert-LastJson $extensionCheck 'Restore extension verification did not return JSON.';Assert-True($extensions.citext-eq$true)'Restore prerequisite missing: citext extension.';Assert-True($extensions.pgcrypto-eq$true)'Restore prerequisite missing: pgcrypto extension.';Write-Step 'Restore prerequisite extensions PASS';Invoke-DockerQuiet @('exec','-e','PGPASSWORD=solidpos',$restoreContainer,'pg_restore','-h','127.0.0.1','-p','5432','-U','postgres','-d','solidpos_restore','--no-owner','--no-privileges','--exit-on-error',"/tmp/$backupName") 'Full pg_restore failed.';Write-Step 'Restore full backup into isolated PostgreSQL PASS'
 Write-Step 'Restored data integrity reconciliation...';$restoreQuery="SELECT json_build_object('tenantCount',(SELECT count(*) FROM pos.tenants WHERE id='$TenantId'::uuid),'storeCount',(SELECT count(*) FROM pos.stores WHERE tenant_id='$TenantId'::uuid),'terminalCount',(SELECT count(*) FROM pos.terminals WHERE tenant_id='$TenantId'::uuid),'userCount',(SELECT count(*) FROM pos.users WHERE tenant_id='$TenantId'::uuid),'salesCount',(SELECT count(*) FROM pos.sales WHERE tenant_id='$TenantId'::uuid),'paymentCount',(SELECT count(*) FROM pos.payments WHERE tenant_id='$TenantId'::uuid),'receiptCount',(SELECT count(*) FROM pos.digital_receipts WHERE tenant_id='$TenantId'::uuid),'returnCount',(SELECT count(*) FROM pos.returns WHERE tenant_id='$TenantId'::uuid),'refundCount',(SELECT count(*) FROM pos.return_refunds WHERE tenant_id='$TenantId'::uuid),'inventoryLedgerCount',(SELECT count(*) FROM pos.inventory_ledger WHERE tenant_id='$TenantId'::uuid),'syncInboxCount',(SELECT count(*) FROM pos.sync_inbox_events WHERE tenant_id='$TenantId'::uuid),'releaseCount',(SELECT count(*) FROM pos.update_releases WHERE tenant_id='$TenantId'::uuid),'releaseTargetCount',(SELECT count(*) FROM pos.update_release_targets WHERE tenant_id='$TenantId'::uuid),'stableReleasePresent',(SELECT count(*) FROM pos.update_releases WHERE id='$($ga06.stableReleaseId)'::uuid AND revoked_at IS NULL)=1)::text;";$restoreOut=Restore-Psql -Name $restoreContainer -PsqlArguments @('-tA','-v','ON_ERROR_STOP=1','-c',$restoreQuery) -Output $true;$restored=Convert-LastJson $restoreOut 'Restore validation did not return JSON.';foreach($n in @('tenantCount','storeCount','terminalCount','userCount','salesCount','paymentCount','receiptCount','returnCount','refundCount','inventoryLedgerCount','syncInboxCount','releaseCount','releaseTargetCount')){Assert-True([long]$restored.$n-eq[long]$source.$n)"Restore count mismatch: $n source=$($source.$n) restored=$($restored.$n)"};Assert-True($restored.stableReleasePresent-eq$true)'Restored stable release missing.';$restoreCompleted=Get-Date;$rto=[math]::Round(($restoreCompleted-$restoreStart).TotalSeconds,3);Assert-True($rto-le$RtoTargetSeconds)"RTO target exceeded: ${rto}s > ${RtoTargetSeconds}s";Write-Step "Restored data integrity reconciliation PASS; rtoSeconds=$rto"
 Write-Step 'Stable application / Velopack rollback transaction drill...';$rollback=Invoke-DbJsonFile $rollbackSql @{tenant_id=$TenantId;stable_release_id=[string]$ga06.stableReleaseId;rollback_version=[string]$ga06.rollbackVersion};Assert-True($rollback.rollbackValidation-eq'GO')'Rollback target unavailable during drill.';Assert-True($rollback.postRollbackValidation-eq'GO'-and$rollback.stableActiveAfterRollback-eq$true)'Stable release not restored after ROLLBACK.';Assert-True([long]$rollback.persistedRollbackMutationCount-eq 0)'Rollback drill persisted a release revoke.';$stableAfter=Invoke-RestMethod -Method Get -Uri "$base/api/v1/updates/check?currentVersion=$([uri]::EscapeDataString([string]$ga06.rollbackVersion))&channel=stable&packageType=velopack&terminalId=$($ga06.targetTerminalId)" -Headers $headers -TimeoutSec 30;Assert-True($stableAfter.updateAvailable-eq$true-and[string]$stableAfter.release.id-eq[string]$ga06.stableReleaseId)'Application stable update path did not recover after rollback drill.';Write-Step 'Stable application / Velopack rollback transaction drill PASS'
 Write-Step 'Post-drill production health and reconciliation...';$readyAfter=Invoke-RestMethod -Method Get -Uri "$base/health/ready" -TimeoutSec 30;Assert-True($readyAfter.status-eq'ready'-and$readyAfter.database-eq'ready')'Readiness failed after drill.';$final=Invoke-DbJsonFile $sourceSql @{tenant_id=$TenantId};Assert-True($final.ga07SqlDecision-eq'GO')"Post-drill blockers: $($final.blockers -join ', ')";foreach($n in @('salesCount','paymentCount','receiptCount','returnCount','refundCount','inventoryLedgerCount','syncInboxCount')){Assert-True([long]$final.$n-eq[long]$source.$n)"Production data changed unexpectedly during drill: $n"};Write-Step 'Post-drill production health and reconciliation PASS'
 Write-Step 'Append rollback/DR audit evidence...';$audit=Invoke-DbJsonFile $auditSql @{tenant_id=$TenantId;stable_release_id=[string]$ga06.stableReleaseId;rollback_version=[string]$ga06.rollbackVersion;rto_seconds=$rto;rpo_seconds=$rpo;trace_id=$traceId};Assert-True($audit.auditDecision-eq'GO'-and[long]$audit.auditCount-eq 1)'GA-07 audit evidence failed.';Write-Step 'Append rollback/DR audit evidence PASS'
 $generated=(Get-Date).ToUniversalTime();$manifest=[ordered]@{phase='GA-07';status='PASS GA BACKUP RESTORE ROLLBACK DISASTER RECOVERY / GO GA-08';tenantId=$TenantId;baseUrl=$base;generatedAt=$generated.ToString('o');entryGate='PASS GA STABLE CHANNEL PROMOTION COHORT DRY RUN / GO GA-07';backupType='PostgreSQL logical full schema+data';backupFormat='pg_dump custom';backupSha256=$backupSha;backupBytes=$backupBytes;backupReadable=$true;restoreIsolation='ephemeral postgres:17 container';restoreValidation='GO';sourceCounts=$source;restoredCounts=$restored;rtoTargetSeconds=$RtoTargetSeconds;rtoSeconds=$rto;rpoTargetSeconds=$RpoTargetSeconds;rpoSeconds=$rpo;stableReleaseId=[string]$ga06.stableReleaseId;stableVersion=[string]$ga06.releaseVersion;rollbackVersion=[string]$ga06.rollbackVersion;rollbackArtifactAvailable=([long]$source.rollbackArtifactValidCount-ge1);rollbackValidation='GO';persistedRollbackMutationCount=[long]$rollback.persistedRollbackMutationCount;postDrillHealth='ready';postDrillDataIntegrity='PASS';rollbackAuditCount=[long]$audit.auditCount;destructiveProductionRestorePerformed=$false;publicRolloutAllowed=$false;productionSigningRequiredBeforePublicPromotion=[bool]$ga06.productionSigningRequiredBeforePublicPromotion;blockers=@();schemaVersion=4;syncContract='schema_version_4';generalAvailabilityActivated=$false;nextPhase='GA-08 - Security, Tenant Isolation and Access Control Final Gate'};$manifest|ConvertTo-Json -Depth 18|Set-Content -Encoding UTF8 $manifestPath;[ordered]@{source=$source;restore=$restored;rollback=$rollback;audit=$audit;manifest=$manifest}|ConvertTo-Json -Depth 20|Set-Content -Encoding UTF8 $snapshotPath
 @"
# GA-07 Backup Restore Rollback Disaster Recovery Evidence

- Backup: full logical `pos` schema + data, custom pg_dump
- Backup SHA-256: $backupSha
- Backup bytes: $backupBytes
- Restore: isolated PostgreSQL 17 container
- Restore integrity: GO
- RPO: ${rpo}s <= ${RpoTargetSeconds}s
- RTO: ${rto}s <= ${RtoTargetSeconds}s
- Stable release: $($ga06.stableReleaseId)
- Rollback version: $($ga06.rollbackVersion)
- Velopack rollback artifact available: true
- persistedRollbackMutationCount: $($rollback.persistedRollbackMutationCount)
- Post-drill health: ready
- Post-drill data integrity: PASS
- rollback audit count: $($audit.auditCount)
- destructive production restore performed: false
- public rollout allowed: false
- generalAvailabilityActivated: false

PASS GA BACKUP RESTORE ROLLBACK DISASTER RECOVERY / GO GA-08
"@|Set-Content -Encoding UTF8 $evidencePath
 @"
# GA-07 Backup Restore Rollback Disaster Recovery Log
- status: $($manifest.status)
- generatedAt: $($manifest.generatedAt)
- backupSha256: $backupSha
- backupBytes: $backupBytes
- restoreValidation: GO
- rpoSeconds: $rpo
- rtoSeconds: $rto
- rollbackValidation: GO
- persistedRollbackMutationCount: $($rollback.persistedRollbackMutationCount)
- rollbackAuditCount: $($audit.auditCount)
- generalAvailabilityActivated: False
"@|Set-Content -Encoding UTF8 $logPath
 Write-Step 'GA-07 evidence manifest and DR snapshot PASS';Write-Step 'GA-07 PASS GA BACKUP RESTORE ROLLBACK DISASTER RECOVERY / GO GA-08';[pscustomobject]$manifest
}
finally{if($containerStarted-and-not$KeepRestoreContainer){docker rm -f $restoreContainer|Out-Null;$global:LASTEXITCODE=0}}
