<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SolidPOS.PosCore.UnitTests</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\PosCore\SolidPOS.PosCore.Application\SolidPOS.PosCore.Application.csproj" />
    <ProjectReference Include="..\..\src\PosCore\SolidPOS.PosCore.Domain\SolidPOS.PosCore.Domain.csproj" />
    <ProjectReference Include="..\..\src\PosCore\SolidPOS.PosCore.Infrastructure\SolidPOS.PosCore.Infrastructure.csproj" />
  </ItemGroup>
</Project>
